sudo: required
services:
  - docker

before_install:
  - docker network create my_net
  - docker image pull redis
  - docker image pull devianspade/flaskpine

script:
  - docker container run --name redised -d --network my_net --network-alias flaskpine-redis redis
  - docker container run --name flaskpined -d --network my_net -p 80:80 devianspade/flaskpine
  
deploy:
  provider: "elasticbeanstalk"
  region: "us-east-2"
  app: "flaskpine"
  env: "Flaskpine-env"
  bucket_name: "elasticbeanstalk-us-east-2-417856445387"
  bucket_path: "flaskpine"

  on:
    branch: "master"
  access_key_id: "$NOT_MY_ID"
  secret_access_key:
    secure: "$NOT_MY_KEY"



# elasticbeanstalk-us-east-2-417856445387