sudo: required
services:
  - docker

before_install:
  - docker swarm init

script:
  - docker stack deploy -c docker-compose.yml flaskpine

deploy:
  provider: "elasticbeanstalk"
  region: "us-east-2"
  app: "flaskpine"
  env: "Flaskpine-env"
  bucket_name: "elasticbeanstalk-us-east-2-417856445387"
  bucket_path: "flaskpine"

  on:
    branch: "master"
  access_key_id: "$NOT_MY_ID"
  secret_access_key:
    secure: "$NOT_MY_KEY"



# elasticbeanstalk-us-east-2-417856445387